// Deliberately authored scenario data. Coordinates locate city centres;
// all indicator values are illustrative and must not be read as official statistics.
export const cities = [
  [
    'copenhagen',
    'Copenhagen',
    'Denmark',
    'Europe',
    55.68,
    12.57,
    1.4,
    89,
    94,
    82,
    32,
    92,
    'A compact city where cycling is part of the everyday rhythm.',
  ],
  [
    'amsterdam',
    'Amsterdam',
    'Netherlands',
    'Europe',
    52.37,
    4.9,
    2.5,
    85,
    93,
    79,
    24,
    93,
    'Short distances and connected neighbourhoods favour life on two wheels.',
  ],
  [
    'vienna',
    'Vienna',
    'Austria',
    'Europe',
    48.21,
    16.37,
    2.0,
    87,
    91,
    65,
    45,
    88,
    'Extensive transit and generous green space share a well-connected urban fabric.',
  ],
  [
    'berlin',
    'Berlin',
    'Germany',
    'Europe',
    52.52,
    13.4,
    3.8,
    80,
    84,
    64,
    33,
    86,
    'An expansive network of neighbourhoods, parks and changing industrial spaces.',
  ],
  [
    'lisbon',
    'Lisbon',
    'Portugal',
    'Europe',
    38.72,
    -9.14,
    2.9,
    70,
    68,
    52,
    22,
    79,
    'Hills, waterfronts and a compact centre create an uneven mobility landscape.',
  ],
  [
    'helsinki',
    'Helsinki',
    'Finland',
    'Europe',
    60.17,
    24.94,
    1.3,
    91,
    88,
    75,
    40,
    95,
    'Coastline and forests sit close to a digitally connected urban core.',
  ],
  [
    'barcelona',
    'Barcelona',
    'Spain',
    'Europe',
    41.39,
    2.17,
    5.6,
    76,
    83,
    59,
    18,
    86,
    'Dense neighbourhoods explore new ways to reclaim street space for daily life.',
  ],
  [
    'london',
    'London',
    'United Kingdom',
    'Europe',
    51.51,
    -0.13,
    9.8,
    74,
    86,
    96,
    33,
    92,
    'A large polycentric city balancing extensive transit with a high cost of living.',
  ],
  [
    'tokyo',
    'Tokyo',
    'Japan',
    'Asia',
    35.68,
    139.69,
    37.2,
    78,
    97,
    71,
    16,
    96,
    'Exceptional rail connectivity supports a vast constellation of local centres.',
  ],
  [
    'singapore',
    'Singapore',
    'Singapore',
    'Asia',
    1.35,
    103.82,
    5.9,
    86,
    90,
    94,
    47,
    98,
    'A compact island city where green infrastructure and digital systems intersect.',
  ],
  [
    'seoul',
    'Seoul',
    'South Korea',
    'Asia',
    37.57,
    126.98,
    25.8,
    75,
    94,
    68,
    27,
    97,
    'A dense, digitally connected metropolis shaped by a powerful transit network.',
  ],
  [
    'taipei',
    'Taipei',
    'Taiwan',
    'Asia',
    25.03,
    121.57,
    7.1,
    73,
    86,
    55,
    25,
    91,
    'Metro lines, lively streets and mountain edges connect many scales of city life.',
  ],
  [
    'melbourne',
    'Melbourne',
    'Australia',
    'Oceania',
    -37.81,
    144.96,
    5.2,
    79,
    76,
    78,
    34,
    90,
    'An outward-growing city with a distinctive tram network and generous parks.',
  ],
  [
    'wellington',
    'Wellington',
    'New Zealand',
    'Oceania',
    -41.29,
    174.78,
    0.4,
    84,
    77,
    73,
    38,
    89,
    'A small coastal capital with a compact centre and a landscape that sets the pace.',
  ],
  [
    'vancouver',
    'Vancouver',
    'Canada',
    'Americas',
    49.28,
    -123.12,
    2.7,
    84,
    79,
    86,
    31,
    92,
    'Mountain and ocean edges frame connected neighbourhoods and housing pressures.',
  ],
  [
    'new-york',
    'New York',
    'United States',
    'Americas',
    40.71,
    -74.01,
    19.5,
    70,
    89,
    100,
    27,
    95,
    'High density and a deep transit network meet a demanding cost of living.',
  ],
  [
    'montreal',
    'Montréal',
    'Canada',
    'Americas',
    45.5,
    -73.57,
    4.3,
    81,
    81,
    64,
    26,
    89,
    'Neighbourhood life, seasonal adaptation and cycling networks shape daily routines.',
  ],
  [
    'bogota',
    'Bogotá',
    'Colombia',
    'Americas',
    4.71,
    -74.07,
    11.5,
    63,
    64,
    32,
    18,
    70,
    'A high-altitude city using cycling and rapid buses to bridge long daily journeys.',
  ],
  [
    'cape-town',
    'Cape Town',
    'South Africa',
    'Africa',
    -33.92,
    18.42,
    4.8,
    62,
    48,
    39,
    30,
    72,
    'A dramatic natural setting meets uneven access to transport and urban services.',
  ],
  [
    'kigali',
    'Kigali',
    'Rwanda',
    'Africa',
    -1.94,
    30.06,
    1.7,
    71,
    51,
    28,
    23,
    67,
    'A growing hill city exploring greener public spaces and new urban infrastructure.',
  ],
].map(
  ([
    id,
    name,
    country,
    region,
    lat,
    lon,
    population,
    sustainability,
    mobility,
    cost,
    green,
    digital,
    description,
  ]) => ({
    id,
    name,
    country,
    region,
    lat,
    lon,
    population,
    sustainability,
    mobility,
    cost,
    green,
    digital,
    description,
  }),
);
export const indicators = {
  sustainability: {
    label: 'Sustainability',
    short: 'Sustainability',
    unit: '/ 100',
    description:
      'A scenario index balancing resource use, energy and environmental planning. Higher is better.',
  },
  mobility: {
    label: 'Urban mobility',
    short: 'Mobility',
    unit: '/ 100',
    description:
      'A scenario index for transit, walking and cycling access. Higher is better.',
  },
  cost: {
    label: 'Cost of living',
    short: 'Cost index',
    unit: '/ 100',
    description:
      'Relative everyday cost, with the New York scenario set to 100. Higher means more expensive.',
  },
  green: {
    label: 'Green space',
    short: 'Green space',
    unit: '%',
    description:
      'Illustrative share of urban land allocated to public green space.',
  },
  digital: {
    label: 'Digital infrastructure',
    short: 'Digital access',
    unit: '/ 100',
    description:
      'A scenario index for connectivity and digital public services. Higher is better.',
  },
  population: {
    label: 'Population',
    short: 'Population',
    unit: 'million',
    description:
      'Illustrative urban-area population in millions; boundaries are not standardised.',
  },
};
export const regions = ['Europe', 'Asia', 'Americas', 'Oceania', 'Africa'];
export const regionColors = {
  Europe: '#d7633b',
  Asia: '#487c78',
  Americas: '#606fa0',
  Oceania: '#ba8c3d',
  Africa: '#7a8560',
};
export function filterCities({
  query = '',
  region = 'All regions',
  minimum = 0,
  sort = 'sustainability',
}) {
  return cities
    .filter(
      (city) =>
        (region === 'All regions' || city.region === region) &&
        (city.name + ' ' + city.country)
          .toLocaleLowerCase()
          .includes(query.toLocaleLowerCase().trim()) &&
        city.sustainability >= Number(minimum),
    )
    .sort((a, b) => b[sort] - a[sort] || a.name.localeCompare(b.name));
}
export function mean(rows, key) {
  return rows.length
    ? rows.reduce((sum, row) => sum + row[key], 0) / rows.length
    : 0;
}
export function csvFor(rows) {
  return [
    'city,country,region,population_millions,sustainability,mobility,cost_index,green_percent,digital',
    ...rows.map((c) =>
      [
        c.name,
        c.country,
        c.region,
        c.population,
        c.sustainability,
        c.mobility,
        c.cost,
        c.green,
        c.digital,
      ].join(','),
    ),
  ].join('\n');
}
